[workspace]
authors = []
channels = ["conda-forge"]
name = "P_D_ISSP_2026"
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
cxx-compiler = ">=1.11.0,<2"
python = "==3.13.9"
ipykernel = ">=7.1.0,<8"

[pypi-dependencies]
numpy = ">=2.4.1, <3"
scipy = ">=1.17.0, <2"
matplotlib = ">=3.10.8, <4"
pyroomacoustics = ">=0.9.0, <0.10"
soundfile = ">=0.13.1, <0.14"
